# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gRd24ad5gLk-WZZgsa31D4UHM4fpgFU
"""

import numpy as np

# -------------------------------
# 1. Dataset Creation
# -------------------------------

# Product Categories
products = np.array(["Rice", "Oil", "Sugar", "Milk", "Soap"])

# Quantity Sold
quantity = np.array([50, 30, 40, 25, 60])

# Unit Price
unit_price = np.array([60, 120, 45, 50, 35])

# Profit percentage
profit_percent = np.array([10, 15, 12, 8, 20])

# -------------------------------
# 2. Broadcasting (Revenue)
# -------------------------------

# Total Sales = Quantity × Unit Price
total_sales = quantity * unit_price

print("Total Sales:", total_sales)

# -------------------------------
# 3. Array Operations
# -------------------------------

total_revenue = np.sum(total_sales)
average_sales = np.mean(total_sales)

print("\nTotal Revenue:", total_revenue)
print("Average Sales:", average_sales)

# -------------------------------
# 4. Indexing and Slicing
# -------------------------------

print("\nFirst Product Sales:", total_sales[0])
print("Top 3 Product Sales:", total_sales[:3])

# -------------------------------
# 5. Statistical Operations
# -------------------------------

print("\nMean Sales:", np.mean(total_sales))
print("Median Sales:", np.median(total_sales))
print("Variance:", np.var(total_sales))
print("Standard Deviation:", np.std(total_sales))

# -------------------------------
# 6. Profit Calculation
# -------------------------------

# Profit using vectorized computation
profit = total_sales * profit_percent / 100

print("\nProfit for each product:", profit)

# -------------------------------
# 7. Interpretation
# -------------------------------

max_sale_index = np.argmax(total_sales)

print("\nBest Selling Product:", products[max_sale_index])
print("Highest Sales Value:", total_sales[max_sale_index])